# Generated by Django 4.2.6 on 2023-12-12 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="заголовок")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=200, verbose_name="слаг"),
                ),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/%Y/%m/%d/", verbose_name="изображение"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                ("created", models.DateField(auto_now_add=True, verbose_name="создан")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
                (
                    "user_like",
                    models.ManyToManyField(
                        blank=True,
                        related_name="images_liked",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="лайкнул",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение",
                "verbose_name_plural": "изображения",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["-created"], name="images_imag_created_d57897_idx"
                    )
                ],
            },
        ),
    ]
